# Page settings
baseurl = "http://Jerad.xyz/elate-inflatabledan/"
title = "Inflatable Dan Boat Service"
languageCode = "en-us"
theme = "hugo-elate-theme"

# setup for GitHub hosting
publishDir = "docs"

[params]

  #custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Inflatable Dan"
  description = "Come to Dan for all your boat needs: repairs and patchwork , custom form and function, or help realize a model from your own imagination, craften with Dan's caring and skillful hands"
  email = "inflatabledan@gmail.com"
  # Navigation
  [params.navigation]
    brand = "Inflatable Dan"
    home = "Home"
    work = "Work"
    testimonials = "Testimonials"
    services = "Services"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "Take care of what you love most."
    subtitle = 'Come to Inflatable Dan and treat you sea vessel to the tender love and care it deserves.'

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Repair"
    description = "No matter how grave the damage: deterioration by neglect or scars by way of adventure. Dan can patch them up, turn it around and have your vessel back in the water and faster than ever."
    url = "#fh5co-work"
    button = "See Dan's Handy Work"
    icon = "icon-wrench"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Enhance"
    description = "'If only she had...' is that horrid nagging that consistently takes even the best of days out to sea down a notch or two. With an incessently dull hum of self-doubt."
    url = "#fh5co-work"
    button = "Get Buff Like These Guys"
    icon = "icon-shield"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Customize"
    description = "If you can dream it, that doesn't mean you should build it. Carring a skillset capable of crafting a sea worthy vessel in novel form, his devotion to the art wont let him construct anything less than legend."
    url = "#fh5co-contact"
    button = "Tell Us Your Dream"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/101450081"


  # Work section
  [params.work]
    enable = true
    title = "Work"
    description = "A short collection of Dan's handy work for your browsing pleasure."
    footertext = '** Interested in seeing more of what Dan can do for you? ** <br> <a href="#fh5co-contact" target="_blank">Get at Dan!</a>'

    [[params.work.row]]
      img = "seahawk.jpg"
      alt = "Custom Inflatable Boat"
      title = "A Client-Designed Dan-Build"
      subtitle = "Custom Boat Build"

    [[params.work.row]]
      img = "boat_names.jpg"
      alt = "Boat Maintenance"
      title = "Freshening Up The Paint"
      subtitle = "Annual Cruiser Maintenance"

    [[params.work.row]]
      img = "cosmic_warloard.jpg"
      alt = "New Deck on Boat"
      title = "Getting a New Topside"
      subtitle = "Refurbishing Cruiser Deck"

    [[params.work.row]]
      img = "rainbow.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "reel_therapy.jpg"
      alt = "Boat Equipment Installation"
      title = "New Season New Gear"
      subtitle = "Rig Assessment & Installation"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"




  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.services.item]]
      title = "Repairs"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Preventative Maintenance"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Experienced Guidance"
      description = "Boats are expensive, and making expensive things float is difficult. Don't wing these decisions uninformed and on your own. Share your thoughts with Dan and you'll be treated to an invaluable discussion that inevitably leaves you self-assured you've got the answer while leaving you absolutely certain you are glad you have Dan to do it."
      icon = "icon-directions"

      [[params.services.item]]
      title = "CMS &amp; eCommerce"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "About"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Jean Smith"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Rob Smith"
      position = "Web Developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Larry Ben"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    title = "Get in touch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Auckland Central, Auckland New Zealand"],
        ["icon-phone", "(022) 370-1452"],
        ["icon-envelope", "IflatableDan@gmail.com"],
        ["icon-social-facebook", '<a href="https://www.facebook.com/Inflatable-dan-280410599027048/" target="_blank">"Inflatable Dan Facebook Page"</a>']
      ]

    name = "Dan"
    email = "InflatableDan@gmail.com"
    phone = "+64 022 370 1452"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Inflatable Dan. All Rights Reserved. <br>Created by <a href="http://Jerad.xyz/" target="_blank">JeradXYZ</a> with help from Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Check me out my thoughts at <a href="irData.com" target="_blank">irData</a> and my projects on GitHub: <a href="https://github.com/irJERAD" target="_blank">irJERAD</a>'
